-- types
INSERT INTO types (name, description) VALUES ('Action', 'Games focused on physical challenges and hand-eye coordination.');
INSERT INTO types (name, description) VALUES ('Strategy', 'Games that emphasize thinking and planning.');
INSERT INTO types (name, description) VALUES ('Simulation', 'Games that simulate real-world activities or situations.');
INSERT INTO types (name, description) VALUES ('Sports', 'Games based on real-world sports, competitions, or athletic activities.');
INSERT INTO types (name, description) VALUES ('Puzzle', 'Games that focus on solving puzzles and challenges.');
INSERT INTO types (name, description) VALUES ('Horror', 'Games designed to scare or unsettle players with horror themes and elements.');
INSERT INTO types (name, description) VALUES ('Platformer', 'Games that involve jumping between suspended platforms and avoiding obstacles.');
INSERT INTO types (name, description) VALUES ('Racing', 'Games centered around competing in races with vehicles or characters.');
INSERT INTO types (name, description) VALUES ('Fighting', 'Games where players engage in hand-to-hand combat or martial arts.');
INSERT INTO types (name, description) VALUES ('Music', 'Games that involve creating music or rhythm-based gameplay.');
INSERT INTO types (name, description) VALUES ('Educational', 'Games designed to teach players specific skills, knowledge, or concepts.');
INSERT INTO types (name, description) VALUES ('Party', 'Games designed for multiplayer enjoyment at social gatherings or parties.');

INSERT INTO videogames (name, price, description, photo) VALUES ('Assassins Creed II', 59.99, 'Immerse yourself in the Renaissance era as Ezio Auditore, a young nobleman turned assassin seeking vengeance. Traverse stunning historical cities, engage in intense stealth missions, and unravel a gripping tale of conspiracy and revenge.', 'https://www.giantbomb.com/a/uploads/scale_medium/9/93770/2392977-assassins_creed_ii_05_artwork.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Cyberpunk 2077', 49.99, 'Immerse yourself in the dystopian future of Night City.', 'https://www.codiciprodotto.it/wp-content/uploads/2021/01/Cyberpunk-2077-PC-COVER.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Kingdom Hearts III', 49.99, 'Embark on a magical journey with Sora, Donald, and Goofy to save various Disney and Pixar worlds.', 'https://cdn11.bigcommerce.com/s-kqbs9oimhc/images/stencil/1280x1280/products/907/2157/88c11e0a782ef4e5738ffce90c125e15__57986.1675454818.jpg?c=1');
INSERT INTO videogames (name, price, description, photo) VALUES ('Dragon Ball Z Budokai Tenkaichi 3', 39.99, 'Embark on an epic journey with Goku and his friends as they strive to become the strongest fighters and defend the Earth against powerful foes.', 'https://i.pinimg.com/564x/64/e7/7e/64e77ea57e593ca330f47ed1ccb682ad.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Grand Theft Auto V', 29.99, 'Enter the sprawling city of Los Santos in this crime-filled adventure.', 'https://hips.hearstapps.com/digitalspyuk.cdnds.net/13/14/gaming-gta5-cover.jpeg?resize=980:*');
INSERT INTO videogames (name, price, description, photo) VALUES ('Minecraft', 19.99, 'Unleash your creativity in the pixelated world of blocks and adventures.', 'https://upload.wikimedia.org/wikinews/en/7/7a/Minecraft_game_cover.jpeg');
INSERT INTO videogames (name, price, description, photo) VALUES ('The Witcher 3: Wild Hunt', 39.99, 'Embark on a journey as Geralt of Rivia, a monster hunter in a vast open world full of quests, creatures, and political intrigue.', 'https://images.gog-statics.com/65f770fa4a2506b5bde93431f4a3a9cbb5bffd027f1bcfaa52c21591453b1df8.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Red Dead Redemption 2', 59.99, 'Experience the epic tale of Arthur Morgan and the Van der Linde gang in the dying days of the Wild West.', 'https://i.pinimg.com/564x/06/1c/61/061c61f8d86361d3d11d5e9796c19d86.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('The Legend of Zelda: Breath of the Wild', 59.99, 'Embark on an adventure across the vast kingdom of Hyrule, solving puzzles and battling enemies to defeat the evil Calamity Ganon.', 'https://i.pinimg.com/564x/64/48/5e/64485ecb5d123a378fd0b17f90cdd356.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Super Mario Odyssey', 49.99, 'Join Mario on a globe-trotting adventure to rescue Princess Peach from Bowser’s wedding plans.', 'https://i.pinimg.com/564x/cd/4d/3d/cd4d3d13447b4f2a51b08dc8bb905c4a.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Dark Souls III', 39.99, 'Prepare to die in the challenging and atmospheric world of Dark Souls III, where danger lurks around every corner.', 'https://i.pinimg.com/564x/9a/37/2d/9a372d1430143ab978d4c63bf8fc7f49.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Uncharted 4: A Thief''s End', 39.99, 'Join Nathan Drake on his final adventure as he searches for hidden treasure and confronts his past.', 'https://i.pinimg.com/564x/6f/4b/30/6f4b30e49b5e5ddbc48c161b66339a2e.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('The Last of Us Part II', 59.99, 'Explore a post-apocalyptic world filled with danger and moral dilemmas as Ellie seeks revenge in this highly anticipated sequel.', 'https://i.pinimg.com/564x/35/48/4e/35484e279f070c8e802a32d1d2c71ed2.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Horizon Zero Dawn', 49.99, 'Embark on a journey with Aloy, a young hunter, in a lush and mysterious world overrun by robotic creatures.', 'https://i.pinimg.com/564x/13/32/8f/13328f07be7f42b13d1d9f5b5f0d6d94.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('God of War', 39.99, 'Join Kratos, the ex-Spartan warrior, and his son Atreus on a brutal journey through the realms of Norse mythology.', 'https://i.pinimg.com/564x/5b/eb/47/5beb47d2a7b2fb7cf56c99c91d9b69d6.jpg');
INSERT INTO videogames (name, price, description, photo) VALUES ('Bloodborne', 29.99, 'Explore the cursed city of Yharnam in this challenging action RPG from the creators of Dark Souls.', 'https://i.pinimg.com/564x/e5/3a/7e/e53a7e458a6e66e98ab84edf47da7416.jpg');

INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-20', 'Supplier F', 17.99, 14, 12);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-19', 'Supplier G', 16.99, 18, 13);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-25', 'Supplier A', 20.99, 19, 11);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-22', 'Supplier D', 18.75, 13, 12);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-23', 'Supplier C', 21.49, 20, 11);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-21', 'Supplier E', 22.99, 17, 12);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-18', 'Supplier H', 25.25, 11, 13);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-17', 'Supplier I', 21.99, 19, 13);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-24', 'Supplier B', 19.99, 20, 11);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-20', 'Supplier F', 27.99, 16, 8);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-19', 'Supplier G', 26.99, 15, 9);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-25', 'Supplier A', 30.99, 11, 7);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-22', 'Supplier D', 28.75, 20, 8);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-23', 'Supplier C', 31.49, 19, 7);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-21', 'Supplier E', 32.99, 17, 8);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-18', 'Supplier H', 35.25, 13, 9);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-17', 'Supplier I', 31.99, 10, 9);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-24', 'Supplier B', 29.99, 15, 7);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-20', 'Supplier F', 37.99, 18, 4);
INSERT INTO stocks (purchase_date, supplier_name, price, quantity, videogame_id) VALUES ('2024-01-19', 'Supplier G', 36.99, 16, 5);

INSERT INTO `role` (name) VALUES('ADMIN');
INSERT INTO `role` (name) VALUES('USER');
INSERT INTO `user` (email, first_name, last_name, password) VALUES('jane@email.com', 'Jane', 'Doe', '{noop}jane');
INSERT INTO `user` (email, first_name, last_name, password) VALUES('john@email.com', 'John', 'Doe', '{noop}john');
INSERT INTO user_role_set (user_id, role_set_name) VALUES(1, 'ADMIN');
INSERT INTO user_role_set (user_id, role_set_name) VALUES(1, 'USER');
INSERT INTO user_role_set (user_id, role_set_name) VALUES(2, 'USER');

INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-29', 7, 4);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-28', 6, 6);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-27', 3, 8);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-26', 6, 10);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-25', 2, 12);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-24', 5, 14);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-23', 7, 16);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-22', 4, 1);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-21', 5, 3);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-29', 3, 5);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-28', 8, 7);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-27', 6, 9);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-26', 4, 11);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-25', 8, 13);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-24', 2, 15);
INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-23', 5, 2);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-22', 1, 4);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-21', 2, 6);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-29', 4, 8);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-28', 1, 10);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-27', 3, 12);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-26', 2, 14);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-25', 4, 16);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-24', 1, 1);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2023-12-23', 3, 3);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (2, '2024-01-22', 5, 5);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2023-12-21', 2, 7);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-29', 4, 9);
--INSERT INTO purchases (user_id, purchase_date, quantity, videogame_id) VALUES (1, '2024-01-28', 1, 11);

INSERT INTO limits (name, `value`) VALUES ("refuelNeededUpperLimit", 200);
INSERT INTO limits (name, `value`) VALUES ("refuelNeededLowerLimit", 100);
INSERT INTO limits (name, `value`) VALUES ("maxPurchasableItems", 50);
